package com.leif.knowme.dao;

import com.leif.knowme.dto.ScheduleItemDto;
import com.leif.knowme.entity.ScheduleItem;
import com.leif.knowme.entity.ScheduleItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ScheduleItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_item
     *
     * @mbg.generated
     */
    long countByExample(ScheduleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_item
     *
     * @mbg.generated
     */
    int deleteByExample(ScheduleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_item
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_schedule_item",
        "where item_id = #{itemId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_item
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_schedule_item (item_id, schedule_id, ",
        "todo_id, plan_start_time, ",
        "real_start_time, plan_end_time, ",
        "real_end_time, consumed, ",
        "order_no, `status`)",
        "values (#{itemId,jdbcType=BIGINT}, #{scheduleId,jdbcType=VARCHAR}, ",
        "#{todoId,jdbcType=VARCHAR}, #{planStartTime,jdbcType=TIMESTAMP}, ",
        "#{realStartTime,jdbcType=TIMESTAMP}, #{planEndTime,jdbcType=TIMESTAMP}, ",
        "#{realEndTime,jdbcType=TIMESTAMP}, #{consumed,jdbcType=INTEGER}, ",
        "#{orderNo,jdbcType=INTEGER}, #{status,jdbcType=INTEGER})"
    })
    int insert(ScheduleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_item
     *
     * @mbg.generated
     */
    int insertSelective(ScheduleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_item
     *
     * @mbg.generated
     */
    List<ScheduleItem> selectByExample(ScheduleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_item
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "item_id, schedule_id, todo_id, plan_start_time, real_start_time, plan_end_time, ",
        "real_end_time, consumed, order_no, `status`",
        "from t_schedule_item",
        "where item_id = #{itemId,jdbcType=BIGINT}"
    })
    @ResultMap("com.leif.knowme.dao.ScheduleItemMapper.BaseResultMap")
    ScheduleItem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ScheduleItem record, @Param("example") ScheduleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ScheduleItem record, @Param("example") ScheduleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ScheduleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_item
     *
     * @mbg.generated
     */
    @Update({
        "update t_schedule_item",
        "set schedule_id = #{scheduleId,jdbcType=VARCHAR},",
          "todo_id = #{todoId,jdbcType=VARCHAR},",
          "plan_start_time = #{planStartTime,jdbcType=TIMESTAMP},",
          "real_start_time = #{realStartTime,jdbcType=TIMESTAMP},",
          "plan_end_time = #{planEndTime,jdbcType=TIMESTAMP},",
          "real_end_time = #{realEndTime,jdbcType=TIMESTAMP},",
          "consumed = #{consumed,jdbcType=INTEGER},",
          "order_no = #{orderNo,jdbcType=INTEGER},",
          "`status` = #{status,jdbcType=INTEGER}",
        "where item_id = #{itemId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ScheduleItem record);

    int insertItems(@Param("scheduleItems") List<ScheduleItem> scheduleItemDos);

    List<ScheduleItemDto> getByScheduleId(String scheduleId);
}