package com.leif.knowme.dao;

import com.leif.knowme.entity.Todo;
import com.leif.knowme.entity.TodoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo
     *
     * @mbggenerated
     */
    int countByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo
     *
     * @mbggenerated
     */
    int deleteByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo
     *
     * @mbggenerated
     */
    @Delete({
        "delete from t_todo",
        "where todo_id = #{todoId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String todoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_todo (todo_id, account_id, ",
        "type, plan_consumed, ",
        "real_consumed, event_msg, ",
        "status, created)",
        "values (#{todoId,jdbcType=VARCHAR}, #{accountId,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=TINYINT}, #{planConsumed,jdbcType=INTEGER}, ",
        "#{realConsumed,jdbcType=INTEGER}, #{eventMsg,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{created,jdbcType=TIMESTAMP})"
    })
    int insert(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo
     *
     * @mbggenerated
     */
    int insertSelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo
     *
     * @mbggenerated
     */
    List<Todo> selectByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "todo_id, account_id, type, plan_consumed, real_consumed, event_msg, status, ",
        "created",
        "from t_todo",
        "where todo_id = #{todoId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Todo selectByPrimaryKey(String todoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_todo
     *
     * @mbggenerated
     */
    @Update({
        "update t_todo",
        "set account_id = #{accountId,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=TINYINT},",
          "plan_consumed = #{planConsumed,jdbcType=INTEGER},",
          "real_consumed = #{realConsumed,jdbcType=INTEGER},",
          "event_msg = #{eventMsg,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "created = #{created,jdbcType=TIMESTAMP}",
        "where todo_id = #{todoId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Todo record);
}