package com.leif.knowme.dao;

import com.leif.knowme.entity.WxUserInfo;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface WxUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_wx_user_info",
        "where open_id = #{openId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_wx_user_info (open_id, session_key, ",
        "nick_name, gender, ",
        "`language`, city, ",
        "privince, country, ",
        "avatarUrl, created)",
        "values (#{openId,jdbcType=VARCHAR}, #{sessionKey,jdbcType=VARCHAR}, ",
        "#{nickName,jdbcType=VARCHAR}, #{gender,jdbcType=TINYINT}, ",
        "#{language,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, ",
        "#{privince,jdbcType=VARCHAR}, #{country,jdbcType=VARCHAR}, ",
        "#{avatarurl,jdbcType=VARCHAR}, #{created,jdbcType=TIMESTAMP})"
    })
    int insert(WxUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "open_id, session_key, nick_name, gender, `language`, city, privince, country, ",
        "avatarUrl, created",
        "from t_wx_user_info",
        "where open_id = #{openId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="session_key", property="sessionKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="nick_name", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.TINYINT),
        @Result(column="language", property="language", jdbcType=JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="privince", property="privince", jdbcType=JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="avatarUrl", property="avatarurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="created", property="created", jdbcType=JdbcType.TIMESTAMP)
    })
    WxUserInfo selectByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "open_id, session_key, nick_name, gender, `language`, city, privince, country, ",
        "avatarUrl, created",
        "from t_wx_user_info"
    })
    @Results({
        @Result(column="open_id", property="openId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="session_key", property="sessionKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="nick_name", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.TINYINT),
        @Result(column="language", property="language", jdbcType=JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="privince", property="privince", jdbcType=JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="avatarUrl", property="avatarurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="created", property="created", jdbcType=JdbcType.TIMESTAMP)
    })
    List<WxUserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user_info
     *
     * @mbg.generated
     */
    @Update({
        "update t_wx_user_info",
        "set session_key = #{sessionKey,jdbcType=VARCHAR},",
          "nick_name = #{nickName,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=TINYINT},",
          "`language` = #{language,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "privince = #{privince,jdbcType=VARCHAR},",
          "country = #{country,jdbcType=VARCHAR},",
          "avatarUrl = #{avatarurl,jdbcType=VARCHAR},",
          "created = #{created,jdbcType=TIMESTAMP}",
        "where open_id = #{openId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(WxUserInfo record);
}