package com.leif.knowme.entity;

import java.util.Date;

/**
 * @author HelloLeif
 */
public class ScheduleItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_item.item_id
     *
     * @mbggenerated
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_item.schedule_id
     *
     * @mbggenerated
     */
    private String scheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_item.todo_id
     *
     * @mbggenerated
     */
    private String todoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_item.plan_start_time
     *
     * @mbggenerated
     */
    private Date planStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_item.real_start_time
     *
     * @mbggenerated
     */
    private Date realStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_item.plan_end_time
     *
     * @mbggenerated
     */
    private Date planEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_item.real_end_time
     *
     * @mbggenerated
     */
    private Date realEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_item.order_no
     *
     * @mbggenerated
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_item.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_item.item_id
     *
     * @return the value of t_schedule_item.item_id
     *
     * @mbggenerated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_item.item_id
     *
     * @param itemId the value for t_schedule_item.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_item.schedule_id
     *
     * @return the value of t_schedule_item.schedule_id
     *
     * @mbggenerated
     */
    public String getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_item.schedule_id
     *
     * @param scheduleId the value for t_schedule_item.schedule_id
     *
     * @mbggenerated
     */
    public void setScheduleId(String scheduleId) {
        this.scheduleId = scheduleId == null ? null : scheduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_item.todo_id
     *
     * @return the value of t_schedule_item.todo_id
     *
     * @mbggenerated
     */
    public String getTodoId() {
        return todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_item.todo_id
     *
     * @param todoId the value for t_schedule_item.todo_id
     *
     * @mbggenerated
     */
    public void setTodoId(String todoId) {
        this.todoId = todoId == null ? null : todoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_item.plan_start_time
     *
     * @return the value of t_schedule_item.plan_start_time
     *
     * @mbggenerated
     */
    public Date getPlanStartTime() {
        return planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_item.plan_start_time
     *
     * @param planStartTime the value for t_schedule_item.plan_start_time
     *
     * @mbggenerated
     */
    public void setPlanStartTime(Date planStartTime) {
        this.planStartTime = planStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_item.real_start_time
     *
     * @return the value of t_schedule_item.real_start_time
     *
     * @mbggenerated
     */
    public Date getRealStartTime() {
        return realStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_item.real_start_time
     *
     * @param realStartTime the value for t_schedule_item.real_start_time
     *
     * @mbggenerated
     */
    public void setRealStartTime(Date realStartTime) {
        this.realStartTime = realStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_item.plan_end_time
     *
     * @return the value of t_schedule_item.plan_end_time
     *
     * @mbggenerated
     */
    public Date getPlanEndTime() {
        return planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_item.plan_end_time
     *
     * @param planEndTime the value for t_schedule_item.plan_end_time
     *
     * @mbggenerated
     */
    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_item.real_end_time
     *
     * @return the value of t_schedule_item.real_end_time
     *
     * @mbggenerated
     */
    public Date getRealEndTime() {
        return realEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_item.real_end_time
     *
     * @param realEndTime the value for t_schedule_item.real_end_time
     *
     * @mbggenerated
     */
    public void setRealEndTime(Date realEndTime) {
        this.realEndTime = realEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_item.order_no
     *
     * @return the value of t_schedule_item.order_no
     *
     * @mbggenerated
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_item.order_no
     *
     * @param orderNo the value for t_schedule_item.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_item.status
     *
     * @return the value of t_schedule_item.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_item.status
     *
     * @param status the value for t_schedule_item.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}