package com.leif.knowme.entity;

import java.util.Date;

public class Todo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_todo.todo_id
     *
     * @mbggenerated
     */
    private String todoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_todo.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_todo.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_todo.plan_consumed
     *
     * @mbggenerated
     */
    private Integer planConsumed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_todo.real_consumed
     *
     * @mbggenerated
     */
    private Integer realConsumed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_todo.event_msg
     *
     * @mbggenerated
     */
    private String eventMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_todo.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_todo.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_todo.todo_id
     *
     * @return the value of t_todo.todo_id
     *
     * @mbggenerated
     */
    public String getTodoId() {
        return todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_todo.todo_id
     *
     * @param todoId the value for t_todo.todo_id
     *
     * @mbggenerated
     */
    public void setTodoId(String todoId) {
        this.todoId = todoId == null ? null : todoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_todo.account_id
     *
     * @return the value of t_todo.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_todo.account_id
     *
     * @param accountId the value for t_todo.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_todo.type
     *
     * @return the value of t_todo.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_todo.type
     *
     * @param type the value for t_todo.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_todo.plan_consumed
     *
     * @return the value of t_todo.plan_consumed
     *
     * @mbggenerated
     */
    public Integer getPlanConsumed() {
        return planConsumed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_todo.plan_consumed
     *
     * @param planConsumed the value for t_todo.plan_consumed
     *
     * @mbggenerated
     */
    public void setPlanConsumed(Integer planConsumed) {
        this.planConsumed = planConsumed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_todo.real_consumed
     *
     * @return the value of t_todo.real_consumed
     *
     * @mbggenerated
     */
    public Integer getRealConsumed() {
        return realConsumed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_todo.real_consumed
     *
     * @param realConsumed the value for t_todo.real_consumed
     *
     * @mbggenerated
     */
    public void setRealConsumed(Integer realConsumed) {
        this.realConsumed = realConsumed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_todo.event_msg
     *
     * @return the value of t_todo.event_msg
     *
     * @mbggenerated
     */
    public String getEventMsg() {
        return eventMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_todo.event_msg
     *
     * @param eventMsg the value for t_todo.event_msg
     *
     * @mbggenerated
     */
    public void setEventMsg(String eventMsg) {
        this.eventMsg = eventMsg == null ? null : eventMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_todo.status
     *
     * @return the value of t_todo.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_todo.status
     *
     * @param status the value for t_todo.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_todo.created
     *
     * @return the value of t_todo.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_todo.created
     *
     * @param created the value for t_todo.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}