package com.leif.knowme.entity;

import java.util.Date;

public class WxUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_info.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_info.session_key
     *
     * @mbg.generated
     */
    private String sessionKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_info.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_info.gender
     *
     * @mbg.generated
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_info.language
     *
     * @mbg.generated
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_info.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_info.privince
     *
     * @mbg.generated
     */
    private String privince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_info.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_info.avatarUrl
     *
     * @mbg.generated
     */
    private String avatarurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_info.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_info.open_id
     *
     * @return the value of t_wx_user_info.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_info.open_id
     *
     * @param openId the value for t_wx_user_info.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_info.session_key
     *
     * @return the value of t_wx_user_info.session_key
     *
     * @mbg.generated
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_info.session_key
     *
     * @param sessionKey the value for t_wx_user_info.session_key
     *
     * @mbg.generated
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_info.nick_name
     *
     * @return the value of t_wx_user_info.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_info.nick_name
     *
     * @param nickName the value for t_wx_user_info.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_info.gender
     *
     * @return the value of t_wx_user_info.gender
     *
     * @mbg.generated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_info.gender
     *
     * @param gender the value for t_wx_user_info.gender
     *
     * @mbg.generated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_info.language
     *
     * @return the value of t_wx_user_info.language
     *
     * @mbg.generated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_info.language
     *
     * @param language the value for t_wx_user_info.language
     *
     * @mbg.generated
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_info.city
     *
     * @return the value of t_wx_user_info.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_info.city
     *
     * @param city the value for t_wx_user_info.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_info.privince
     *
     * @return the value of t_wx_user_info.privince
     *
     * @mbg.generated
     */
    public String getPrivince() {
        return privince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_info.privince
     *
     * @param privince the value for t_wx_user_info.privince
     *
     * @mbg.generated
     */
    public void setPrivince(String privince) {
        this.privince = privince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_info.country
     *
     * @return the value of t_wx_user_info.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_info.country
     *
     * @param country the value for t_wx_user_info.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_info.avatarUrl
     *
     * @return the value of t_wx_user_info.avatarUrl
     *
     * @mbg.generated
     */
    public String getAvatarurl() {
        return avatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_info.avatarUrl
     *
     * @param avatarurl the value for t_wx_user_info.avatarUrl
     *
     * @mbg.generated
     */
    public void setAvatarurl(String avatarurl) {
        this.avatarurl = avatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_info.created
     *
     * @return the value of t_wx_user_info.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_info.created
     *
     * @param created the value for t_wx_user_info.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}